### ISSUE TITLE
"Follow" key doesn't work on MacOS

### ISSUE THREAD

**Issue by rm-code** [FluffierThanThou/FollowMe#28]
**Describe the bug**  
Pressing the "follow"-key doesn't do anything regardless of which key it is actually bound to. The cinematic camera seems to work fine though.

**Expected behavior**  
Pressing "follow"-key should toggle follow action.

**Steps to reproduce**  
Happens on new and loaded savegames.

1. Select colonist
2. Press "follow"-key
3. Nothing happens

**Other mods**  
- brrainz.harmony
- ludeon.rimworld
- fluffy.followme

**Output log**  
Currently on my lunch break at work so I can't provide a log (not even sure if there is a log on MacOS).

**Save game**  
N/A

**Screenshots**  
N/A

**Environment**  
 - OS: Mac OS Catalina
 
**Game**
 - 64 bits
 - Steam
 - Version 1.1.2589

**Comment by FluffierThanThou** [comment]
is hopefully fixed by the new keybinging system. Please let me know if it isn't.
