### ISSUE TITLE
FollowMe does not let go of camera when middle mouse button is held

### ISSUE THREAD

**Issue by Pichu0102** [FluffierThanThou/FollowMe#8]
When holding the middle mouse button down and moving the mouse, FollowMe fights the player and keeps moving it back to the FollowMe target instead of relinquishing camera control.

Logs:
https://gist.github.com/b9d090ec6a35bba82c5fb102af4e97fe

**Comment by FluffierThanThou** [comment]
fixed in 0.17.0.0
